version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.5'
    working_directory: ~/hallingdata.no
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: null
        name: Build
        command: npm run build
  deploy:
    machine:
      enabled: true
    working_directory: ~/hallingdata.no
    steps:
      - run: null
        name: Publish to GitHub Pages
        command: npm run publish
