backend:
  name: git-gateway
  branch: master
media_folder: static/img/uploads
public_folder: /img/uploads
collections:
  - name: hjem
    label: Hjem
    folder: src/content
    filter:
      field: pageName
      value: Hjem
    create: false
    fields:
      - label: pageName
        name: pageName
        widget: hidden
      - label: Meta Title
        name: metaTitle
        widget: string
      - label: Meta Description
        name: metaDescription
        widget: string
      - label: Meta URL
        name: metaUrl
        widget: string
      - label: Overskrift
        name: header
        widget: string
      - label: Overskrift facebook oppdateringer
        name: facebookPostsHeader
        widget: string
      - label: Facebook Posts
        name: facebookPosts
        widget: list
      - label: Tjenester
        name: ourServices
        widget: list
        fields:
          - label: Titel
            name: header
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Ikon
            name: icon
            widget: string
          - label: Link til side
            name: link
            widget: string
      - label: Team title
        name: teamHeader
        widget: string
      - label: Team
        name: team
        widget: list
        fields:
          - label: Navn
            name: name
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Linkedin
            name: linkedinUrl
            widget: string
            required: false
          - label: GitHub
            name: githubUrl
            widget: string
            required: false
      - label: Kunder logoer overskrift
        name: customerLogoHeader
        widget: string
  - name: nettside
    label: Nettside
    folder: src/content
    filter:
      field: pageName
      value: Nettside
    create: false
    fields:
      - label: pageName
        name: pageName
        widget: hidden
      - label: Meta Title
        name: metaTitle
        widget: string
      - label: Meta Description
        name: metaDescription
        widget: string
      - label: Meta URL
        name: metaUrl
        widget: string
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
      - label: Sjekkliste overskrift
        name: checklistHeader
        widget: string
      - label: Sjekkliste
        name: checklist
        widget: list
      - label: Portfolio overskrift
        name: portfolioHeader
        widget: string
      - label: Portfolio
        name: portfolio
        widget: list
        fields:
          - label: Titel
            name: title
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Nettaddresse
            name: url
            widget: string
  - name: app
    label: App
    folder: src/content
    filter:
      field: pageName
      value: App
    create: false
    fields:
      - label: pageName
        name: pageName
        widget: hidden
      - label: Meta Title
        name: metaTitle
        widget: string
      - label: Meta Description
        name: metaDescription
        widget: string
      - label: Meta URL
        name: metaUrl
        widget: string
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
      - label: Sjekkliste overskrift
        name: checklistHeader
        widget: string
      - label: Sjekkliste
        name: checklist
        widget: list
      - label: Tjenester
        name: ourServices
        widget: list
        fields:
          - label: Titel
            name: header
            widget: string
          - label: Tekst
            name: description
            widget: text
          - label: Ikon
            name: icon
            widget: string
  - name: Systemutvikling
    label: Systemutvikling
    folder: src/content
    filter:
      field: pageName
      value: Systemutvikling
    create: false
    fields:
      - label: pageName
        name: pageName
        widget: hidden
      - label: Meta Title
        name: metaTitle
        widget: string
      - label: Meta Description
        name: metaDescription
        widget: string
      - label: Meta URL
        name: metaUrl
        widget: string
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
      - label: Sjekkliste overskrift
        name: checklistHeader
        widget: string
      - label: Sjekkliste
        name: checklist
        widget: list
      - label: Teknologier overskrift
        name: technologiesHeader
        widget: string
      - label: Teknologier
        name: technologies
        widget: list
  - name: Om oss
    label: Om oss
    folder: src/content
    filter:
      field: pageName
      value: Om oss
    create: false
    fields:
      - label: pageName
        name: pageName
        widget: hidden
      - label: Meta Title
        name: metaTitle
        widget: string
      - label: Meta Description
        name: metaDescription
        widget: string
      - label: Meta URL
        name: metaUrl
        widget: string
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
  - name: Kontakt
    label: Kontakt
    folder: src/content
    filter:
      field: pageName
      value: Kontakt
    create: false
    fields:
      - label: pageName
        name: pageName
        widget: hidden
      - label: Meta Title
        name: metaTitle
        widget: string
      - label: Meta Description
        name: metaDescription
        widget: string
      - label: Meta URL
        name: metaUrl
        widget: string
      - label: Overskrift
        name: header
        widget: string
      - label: Kontaktskjema overskrift
        name: contactFormHeader
        widget: string
      - label: Tekst
        name: body
        widget: markdown
      - label: Kontakt info
        name: contactList
        widget: list
        fields:
          - label: Kontakt overskrift
            name: header
            widget: string
          - label: Kontakt
            name: contact
            widget: string
          - label: Kontakt info
            name: info
            widget: text
          - label: Ikon
            name: icon
            widget: string
  - name: Kontakt takk
    label: Kontakt takk
    folder: src/content
    filter:
      field: pageName
      value: Takk
    create: false
    fields:
      - label: pageName
        name: pageName
        widget: hidden
      - label: Meta Title
        name: metaTitle
        widget: string
      - label: Meta Description
        name: metaDescription
        widget: string
      - label: Meta URL
        name: metaUrl
        widget: string
      - label: Overskrift
        name: header
        widget: string
      - label: Tekst
        name: body
        widget: markdown
